//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Puesto> PuestoSet { get; set; }
        public virtual DbSet<Registro_transaccion_deduccion> Registro_transaccion_deduccionSet { get; set; }
        public virtual DbSet<Empleado> EmpleadoSet { get; set; }
        public virtual DbSet<Departamento> DepartamentoSet { get; set; }
        public virtual DbSet<Tipo_de_Deduccion> Tipo_de_DeduccionSet { get; set; }
        public virtual DbSet<Tipo_de_Ingreso> Tipo_de_IngresoSet { get; set; }
        public virtual DbSet<Registro_Transaccion> Registro_TransaccionSet { get; set; }
        public virtual DbSet<Nivel_Riesgo> Nivel_RiesgoSet { get; set; }
    }
}
