//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registro_transaccion_deduccion
    {
        public int Id_Transaccion_deduccion { get; set; }
        public int Id_Empleado { get; set; }
        public int Id_Tipo_Deducc { get; set; }
        public System.DateTime Fecha { get; set; }
        public double Monto { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Tipo_de_Deduccion Tipo_de_Deduccion { get; set; }
    }
}
