USE [master]
GO

/****** Object:  Database [INYECCION_SQL]    Script Date: 26/07/2021 18:40:38 ******/
CREATE DATABASE [INYECCION_SQL] ON  PRIMARY 
( NAME = N'INYECCION_SQL', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSALEIDA\MSSQL\DATA\INYECCION_SQL.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'INYECCION_SQL_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.SQLEXPRESSALEIDA\MSSQL\DATA\INYECCION_SQL_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [INYECCION_SQL].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [INYECCION_SQL] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET ARITHABORT OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [INYECCION_SQL] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [INYECCION_SQL] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET  DISABLE_BROKER 
GO

ALTER DATABASE [INYECCION_SQL] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [INYECCION_SQL] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [INYECCION_SQL] SET  MULTI_USER 
GO

ALTER DATABASE [INYECCION_SQL] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [INYECCION_SQL] SET DB_CHAINING OFF 
GO

ALTER DATABASE [INYECCION_SQL] SET  READ_WRITE 
GO


